In [ ]:
import numpy as np

In [4]:
mylist = [1,2,3]
type(mylist)

list

In [10]:
# convert python arrays into numpy arrays
array1 = np.array(mylist)
type(array1)

numpy.ndarray

In [11]:
# numpy's version of range()
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
# create a new array intialized with 0 with shape. These are 0. which is a floating point
array2 = np.zeros(shape=(5,5))
print(array2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
np.random.seed(101)
# generate 10 random numbers from 0 to 99
arr = np.random.randint(0,100,10)
print(arr)

[95 11 81 70 63 87 75  9 77 40]


In [33]:
arr.max() # Max value in the list

95

In [36]:
arr.argmax() # Index for the max value

0

In [39]:
arr.mean()

60.8

In [43]:
arr.reshape((2,5)) # Cannot do this operation with number of elements vs rows/columns that dont make sense

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [46]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
mat[0,:] # all items in row 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
mat[:,0] # all items in column 0

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
mat[:,0].reshape(10,1) # returning a column reshaped

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [59]:
# grabbing a 3x3 block
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [62]:
# perform a shallow copy
copymat = mat.copy()
copymat[0,:] = -1
copymat

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])